name = "redirect-joshthomasdev"
main = "src/index.ts"
compatibility_date = "2024-01-18"

routes = [
	{ pattern = "joshuadavidthomas.com", custom_domain = true }
]

[vars]
REDIRECT_STATUS_CODE = 307
TARGET_DOMAIN = "joshthomas.dev"

